import { z } from 'zod';

// Priority levels for opportunities
export enum OpportunityPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

// Status options for opportunities
export enum OpportunityStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  AWARDED = 'AWARDED',
  LOST = 'LOST',
}

// Zod schema for the Opportunity
export const opportunitySchema = z.object({
  id: z.string().optional(), // Auto-generated by Firestore
  name: z.string().min(3, { message: 'Name must be at least 3 characters' }),
  client: z.string().min(2, { message: 'Client name is required' }),
  sbu: z.string().min(1, { message: 'Strategic Business Unit is required' }),
  value: z.number().nonnegative({ message: 'Value must be non-negative' }),
  grossMargin: z.number().min(0).max(100, { message: 'Gross margin must be between 0-100%' }),
  priority: z.nativeEnum(OpportunityPriority),
  status: z.nativeEnum(OpportunityStatus),
  rfpDue: z.date(),
  internalDeadline: z.date(),
  ownerUid: z.string(),
  createdAt: z.date().optional(), // Will be set in converter
  updatedAt: z.date().optional(), // Will be set in converter
  assignedTo: z.array(z.string()).default([]),
});

// TypeScript type derived from the Zod schema
export type Opportunity = z.infer<typeof opportunitySchema>;

// Type for creating a new opportunity
export const createOpportunitySchema = opportunitySchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type CreateOpportunityInput = z.infer<typeof createOpportunitySchema>;

// Type for updating an existing opportunity
export const updateOpportunitySchema = opportunitySchema
  .partial()
  .omit({ id: true, createdAt: true, updatedAt: true });
export type UpdateOpportunityInput = z.infer<typeof updateOpportunitySchema>;

// Response type for opportunity operations
export type OpportunityResponse = {
  success: boolean;
  opportunity?: Opportunity;
  error?: string;
}; 